apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    app: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: 211125721901.dkr.ecr.us-east-1.amazonaws.com/shopping-site-home:4c15f98ed6d08fb0159b02a50d33d6726975fd84
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
  labels:
    app: home
spec:
  type: ClusterIP
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
